name: build
on: push
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules : recursive
    - uses: actboy168/setup-luamake@master
    - run: luamake
    - run: luamake runtest
